--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/IcyEndymion004/Gkit-shards-from-a-plugin-i-was-scammed-
build-by-default: true
branches:
- API3
- API-4-Branch
projects:
  GKitShards_v1.0.0:
    path: ""
    icon: "profile.png"
...
