name: InventoryShards
version: 0.0.9
api: 3.0.0
main: IcyEndymion004\GkitShards\Loader
author: IcyEndymion004
website: https://github.com/IcyEndymion004/Inventory-Shards/
commands:
  setshardinv:
    description: "Sets Your Inventory As A Shard"
    permission: inventory.command.setshard
  giveshard:
    description: "Gives You A Inventory Shard"
    permission: inventory.command.giveshard
  seeshardinfo:
    description: "Allows You To See Into A Shards Inventory"
permissions:
  inventory.command.setshard:
    description: SetShard Command Perm
    default: op
  inventory.command.giveshard:
    description: GiveShard Command Perm
    default: op
  inventory.command.seeshard:
    description: SeeShardinfo Command Perm
    default: op
