name: InventoryShards
version: 0.0.5
api: 3.0.0
main: IcyEndymion004\GkitShards\Loader
author: IcyEndymion004
website: https://github.com/IcyEndymion004/Inventory-Shards

commands:
  setshardinv:
    description: "Sets Your Inventory As A Shard"
  giveshard:
    description: "Gives You A Inventory Shard"
