name: GkitShards
version: 0.0.2
api: 3.0.0
main: IcyEndymion004\GkitShards\Loader
author: IcyEndymion004
website: https://github.com/IcyEndymion004/GShards--was-from-a-scam-

commands:
  setshardinv:
    description: "Set shard inv"
  giveshard:
    description: "Give shard inv"
