---
#DONT CHANGE THE CONFIG VERSION AS IT WELL BREAK EVERYTHING
config-version: 0.6
#-------------------------------------------Messages--------------------------------------------------------------
# Color thing: ยง
# https://www.digminecraft.com/lists/color_list_pc.php For color stuff
NoRoomMessage: "Your inventory doesn't have room!"
NoShardexists:  "does not exist." #this is after the shard name is there so the name of the shard is there 
SetInvasShard: "Set your inventory to the shard type: "
#-----------------------------------------------------------------------------------------------------------------
type-shards:
  typeshard1:
    item-name: "Shard1"
    item-lore:
      - "Lore line 1."
      - "Lore line 2."
      - "Lore Line 3"
      - "Lore Line 4"
...
