---
#DONT CHANGE THE CONFIG VERSION AS IT WELL BREAK EVERYTHING
config-version: 0.4
type-shards:
  typeshard1:
    item-name: "Shard1"
    item-lore:
      - "Lore line 1."
      - "Lore line 2."
...
