---

#DONT CHANGE THE CONFIG VERSION AS IT WELL BREAK EVERYTHING
config-version: 1.0.0
EconamyEnabled: true #Please make sure you Have EconomyAPI Working On Your server
#-------------------------------------------Messagestypes---------------------------------------------------------
# 1 = message
# 2 = popup
# 3 = title
NoShardExistsType: 2
SetinvshardType: 2
giveshardType: 2
typeNoRoomMessage: 2
typeToPoor: 2
typeEditShard: 2
#-------------------------------------------Messages--------------------------------------------------------------
# Color thing: §
# https://www.digminecraft.com/lists/color_list_pc.php For color stuff
ToPoor: "§cYou Need§6 {cost} §cTo Claim This Shard"
NoRoomMessage: "§cYour inventory doesn't have room!" #There Are No Custom Tags For This Message
NoShardexistsmsg:  "§cThe §6{shard} §cShard Does Not Exist" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
SetInvasShardmsg: "§aYou Have Set Inventory Of §6{player} §aAs The §6{shard} §aShard" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
InvaidShard: "§6{shard} §cIs Not Vaild" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
GivenShardMsg: "§6{player} §aHas Been Given §6{shard}" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
ShardEditComplete: "§aYou Have Updated§6 {shard} 's §aContents" #Custom Tags: {player} = The Name Of The Sender {shard} = The Name Of The Thing You Entered For A Shard
#--------------------------------------------UI--------------------------------------------------------------------
UIName: "§8[§1§4!§r§8] §eShards §cList §8[§1§4!§r§8]"
UIButtonFormat: "§c§l {shard} \n §r§9Click To Get Shard"
UICloseButton: "§cClose"
#--------------------------------------------GUI-------------------------------------------------------------------
GUIname: "§6{shard} §1Data" #Custom Tags:
#--------------------------------------------Shards----------------------------------------------------------------
type-shards:
  typeshard1:
    shardID: '450' 
    ShardMeta: '0'
    claimcost: "15" #must be an int
    item-name: "Shard1"
    item-lore:
      - "Lore line 1."
      - "Lore line 2."
      - "Lore Line 3."
      - "Lore Line 4."
  typeshard2:
    shardID: '450' 
    ShardMeta: '0'
    claimcost: "15"
    item-name: "Shard1"
    item-lore:
      - "Lore line 1."
      - "Lore line 2."
      - "Lore Line 3."
      - "Lore Line 4."
...
